### ISSUE TITLE
[msan] Don't understand the failure either

### ISSUE THREAD

**Issue by behdad** [harfbuzz/harfbuzz#1175]
The code looks correct to me.  Not sure what's going on.  Guess we can disable it for now.. file bug with msan...
```
behdad:msanbuild 0$ asan_symbolize< ./test/shaping/data/in-house/tests/arabic-fallback-shaping.log | c++filt 
Running tests in ../../../../../test/shaping/data/in-house/tests/arabic-fallback-shaping.tests
../../../../util/hb-shape ../../../../../test/shaping/data/in-house/fonts/df768b9c257e0c9c35786c47cae15c46571d56be.ttf --verify  --unicodes U+0633,U+064F,U+0644,U+064E,U+0651,U+0627,U+0651,U+0650,U+0645,U+062A,U+06CC
==146709==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x49c6fc in g_string_append_c_inline(_GString*, char) /home/behdad/.local/include/glib-2.0/glib/gstring.h:164
    #1 0x49c6fc in ?? ??:0
    #2 0x49be04 in font_options_t::add_options(option_parser_t*) /home/behdad/SSD/src/freedesktop/harfbuzz/msanbuild/util/../../util/options.cc:534
    #3 0x49be04 in ?? ??:0
    #4 0x495e93 in main_font_text_t /home/behdad/SSD/src/freedesktop/harfbuzz/msanbuild/util/../../util/main-font-text.hh:55
    #5 0x495e93 in ?? ??:0
    #6 0x495c16 in main /home/behdad/SSD/src/freedesktop/harfbuzz/msanbuild/util/../../util/hb-shape.cc:163
    #7 0x495c16 in ?? ??:0
    #8 0x7fa3244692b0 in __libc_start_main /tmp/build-debs.Lfl5zt/glibc-2.24/csu/../csu/libc-start.c:291
    #9 0x7fa3244692b0 in ?? ??:0
    #10 0x41f439 in _start ??:?
    #11 0x41f439 in ?? ??:0

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/behdad/SSD/src/freedesktop/harfbuzz/msanbuild/util/.libs/hb-shape+0x49c6fc)
Exiting
```

**Comment by behdad** [comment]
Also, looks like msan exists with status 77 on error, which means "skip test" to automake.

**Comment by behdad** [comment]
> Also, looks like msan exists with status 77 on error, which means "skip test" to automake.

MSAN_OPTIONS=exitcode=42

**Comment by behdad** [comment]
The other one, strlen-related, also looks equally suspicious:
```
behdad:api 1$ asan_symbolize < test-blob.log 
Uninitialized bytes in __interceptor_strlen at offset 66 inside [0x705000000050, 67)
==120354==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f4970639b08 in g_str_has_suffix ./debian/build/deb/glib/../../../../glib/gstrfuncs.c:2850
    #1 0x7f4970639b08 in ?? ??:0
    #2 0x7f497063e32f in g_test_init ./debian/build/deb/glib/../../../../glib/gtestutils.c:1212
    #3 0x7f497063e32f in ?? ??:0
    #4 0x49169e in main /home/behdad/SSD/src/freedesktop/harfbuzz/msanbuild/test/api/../../../test/api/test-blob.c:331
    #5 0x49169e in ?? ??:0
    #6 0x7f496f70a2b0 in __libc_start_main /tmp/build-debs.Lfl5zt/glibc-2.24/csu/../csu/libc-start.c:291
    #7 0x7f496f70a2b0 in ?? ??:0
    #8 0x41d4f9 in _start ??:?
    #9 0x41d4f9 in ?? ??:0

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x6bb08)
Exiting
```

**Comment by behdad** [comment]
Closing as per other bug.  We need to build glib with msan, which probably takes too long with our current bots.  Disabling msan again.

**Comment by khaledhosny** [comment]
We probably can build and cache GLib (we probably should cache Freetype when built from source). Worth trying.

**Comment by khaledhosny** [comment]
Or use ccache and cache its directory, might even make building HarfBuzz itself faster.

**Comment by behdad** [comment]
Oh yeah I forgot about the caching stuff.  Does CircleCI have that as well?  Travis did.

**Comment by khaledhosny** [comment]
Seems so.
