### ISSUE TITLE
[msan] Fix the bot

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#1199]
Now that the bots builds both glib and freetype with the flags we should fix its issues I believe,

```diff
diff --git a/test/api/hb-test.h b/test/api/hb-test.h
index 307845f6..a7785c1c 100644
--- a/test/api/hb-test.h
+++ b/test/api/hb-test.h
@@ -183,7 +183,7 @@ hb_test_add_func (const char *test_path,
   g_test_add_func (normal_path, test_func);
   g_free (normal_path);
 }
-#define hb_test_add(Func) hb_test_add_func (#Func, Func)
+#define hb_test_add(Func) hb_test_add_func (#Func "\0", Func)
```

And replace `g_string_append_c (gs, '?');`s to `g_string_append (gs, "?");` and the complain now is,

```
Uninitialized bytes in __interceptor_strlen at offset 8 inside [0x701000000190, 9)
==29184==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f0df596a1b2 in g_strdup ??:?
    #1 0x7f0df596a1b2 in ?? ??:0
    #2 0x7f0df597f4a3 in g_set_prgname ??:?
    #3 0x7f0df597f4a3 in ?? ??:0
    #4 0x7f0df5957715 in g_option_context_parse ??:?
    #5 0x7f0df5957715 in ?? ??:0
    #6 0x4a497e in option_parser_t::parse(int*, char***) /home/ebrahim/Desktop/harfbuzz/build/util/../../util/options.cc:155
    #7 0x4a497e in ?? ??:0
    #8 0x4a05dc in main_font_text_t<shape_consumer_t<output_buffer_t>, 2147483647, 0>::main(int, char**) /home/ebrahim/Desktop/harfbuzz/build/util/../../util/main-font-text.hh:62
    #9 0x4a05dc in ?? ??:0
    #10 0x4a039e in main /home/ebrahim/Desktop/harfbuzz/build/util/../../util/hb-shape.cc:164
    #11 0x4a039e in ?? ??:0
    #12 0x7f0df46aab96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #13 0x7f0df46aab96 in ?? ??:0
    #14 0x41d459 in _start ??:?
    #15 0x41d459 in ?? ??:0
```

Any hope?

**Comment by behdad** [comment]
Still looks non-instrumented glib to me.  Humm?

**Comment by ebraminio** [comment]
The bot is using this,

`
wget https://ftp.gnome.org/pub/gnome/sources/glib/2.28/glib-2.28.0.tar.bz2 && tar xf glib-2.28.0.tar.bz2 && cd glib-2.28.0 && CPPFLAGS="-fsanitize=memory" LDFLAGS="-fsanitize=memory" CFLAGS="-fsanitize=memory" CXXFLAGS="-fsanitize=memory" LD=ld.lld CC=clang CXX=clang++ ./autogen.sh || true && ./configure && make -j32 --ignore-errors && cd ..
`

And I have the same issue locally, is that not enough?

**Comment by ebraminio** [comment]
https://circleci.com/gh/harfbuzz/harfbuzz/35170

And apparently msan bot is using that build,

```
FAIL test-font (exit status: 42)
==== ./test/api/test-subset-hmtx.log ====
Uninitialized bytes in __interceptor_strchr at offset 6 inside [0x701000000030, 7)
==50969==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f96fe2c88eb in g_test_create_suite /root/project/glib-2.28.0/glib/gtestutils.c:1062
    #1 0x7f96fe2c88eb in ?? ??:0
    #2 0x7f96fe2c8b62 in g_test_add_vtable /root/project/glib-2.28.0/glib/gtestutils.c:975
    #3 0x7f96fe2c8b62 in ?? ??:0
    #4 0x49556b in hb_test_add_func /root/project/test/api/./hb-test.h:183
    #5 0x49556b in ?? ??:0
    #6 0x495438 in main /root/project/test/api/test-subset-hmtx.c:178
    #7 0x495438 in ?? ??:0
    #8 0x7f96fdccc09a in __libc_start_main ??:?
    #9 0x7f96fdccc09a in ?? ??:0
    #10 0x41c3f9 in _start ??:?
    #11 0x41c3f9 in ?? ??:0
```

**Comment by ebraminio** [comment]
Maybe because of "--ignore-errors" I've put, some parts of glib is using system's? Anyway the bot SSH is also available if one wants to see how it should be fixed.

**Comment by behdad** [comment]
Don't know.  Won't have time to figure it out soon.  But the error looks suspicious.

**Comment by ebraminio** [comment]
Great, now we have something here

https://circleci.com/gh/harfbuzz/harfbuzz/35319

Behdad, can you have a look?

**Comment by behdad** [comment]
> Behdad, can you have a look?

Fixed.

**Comment by behdad** [comment]
Bot much better.  Disabled ICU and cairo.  I expect it should become green now.

(Unrelated, we should --with-fontconfig explicitly, at least in a few bots.)
