### ISSUE TITLE
Allocation failure causes a dereference of NULL

### ISSUE THREAD

**Issue by sebras** [harfbuzz/harfbuzz#2501]
More testing of memory allocation failing using clang+ASAN revealed a `NULL` dereference in HarfBuzz 2.6.4, which still seems to be present in git HEAD. This is the fourth and final issue I've discovered this way.

The crash occurs due to dereferencing of `NULL`  here:

```
    #0 0xd312fc in hb_ft_font_changed harfbuzz/src/hb-ft.cc:712:30
    #1 0xd310ee in hb_ft_font_create harfbuzz/src/hb-ft.cc:701:3
```

To get into this situation `calloc()` must first return `NULL` here:

```
#0  0x0000000000d22887 in hb_object_create<hb_font_funcs_t> () at harfbuzz/src/hb-object.hh:227
#1  0x0000000000d227fd in hb_font_funcs_create () at harfbuzz/src/hb-font.cc:532
#2  0x0000000000d3aead in hb_ot_font_funcs_lazy_loader_t::create () at harfbuzz/src/hb-ot-font.cc:257
#3  0x0000000000d3ae21 in hb_data_wrapper_t<void, 0u>::call_create<hb_font_funcs_t, hb_ot_font_funcs_lazy_loader_t> (this=0x4256220 <static_ot_funcs>) at harfbuzz/src/hb-machinery.hh:171
#4  0x0000000000d3ad86 in hb_lazy_loader_t<hb_font_funcs_t, hb_ot_font_funcs_lazy_loader_t, void, 0u, hb_font_funcs_t>::get_stored (this=0x4256220 <static_ot_funcs>) at harfbuzz/src/hb-machinery.hh:222
#5 0x0000000000d3acf5 in hb_lazy_loader_t<hb_font_funcs_t, hb_ot_font_funcs_lazy_loader_t, void, 0u, hb_font_funcs_t>::get_unconst (this=0x4256220 <static_ot_funcs>) at harfbuzz/src/hb-machinery.hh:247
#6 0x0000000000d3a163 in _hb_ot_get_font_funcs () at harfbuzz/src/hb-ot-font.cc:296
#7 0x0000000000d3a0e9 in hb_ot_font_set_funcs (font=0x60d0000006c8) at harfbuzz/src/hb-ot-font.cc:309
#8 0x0000000000d2b2c2 in hb_font_create (face=0x6140000c8648) at harfbuzz/src/hb-font.cc:1380
#9 0x0000000000d310ca in hb_ft_font_create (ft_face=0x61a000003088, destroy=0x0) at harfbuzz/src/hb-ft.cc:698
```

Next `calloc()` returns `NULL` here:

```
#0  0x0000000000d22887 in hb_object_create<hb_font_funcs_t> () at harfbuzz/src/hb-object.hh:227
#1  0x0000000000d227fd in hb_font_funcs_create () at harfbuzz/src/hb-font.cc:532
#2  0x0000000000d323dd in hb_ft_font_funcs_lazy_loader_t::create () at harfbuzz/src/hb-ft.cc:512
#3  0x0000000000d32351 in hb_data_wrapper_t<void, 0u>::call_create<hb_font_funcs_t, hb_ft_font_funcs_lazy_loader_t> (this=0x42561a0 <static_ft_funcs>) at harfbuzz/src/hb-machinery.hh:171
#5  0x0000000000d32276 in hb_lazy_loader_t<hb_font_funcs_t, hb_ft_font_funcs_lazy_loader_t, void, 0u, hb_font_funcs_t>::get_stored (this=0x42561a0 <static_ft_funcs>) at harfbuzz/src/hb-machinery.hh:222
#6 0x0000000000d321e5 in hb_lazy_loader_t<hb_font_funcs_t, hb_ft_font_funcs_lazy_loader_t, void, 0u, hb_font_funcs_t>::get_unconst (this=0x42561a0 <static_ft_funcs>) at harfbuzz/src/hb-machinery.hh:247
#7 0x0000000000d31fd3 in _hb_ft_get_font_funcs () at harfbuzz/src/hb-ft.cc:553
#8 0x0000000000d311f6 in _hb_ft_font_set_funcs (font=0x60d0000006c8, ft_face=0x61a000003088, unref=false) at harfbuzz/src/hb-ft.cc:562
#9 0x0000000000d310e6 in hb_ft_font_create (ft_face=0x61a000003088, destroy=0x0) at harfbuzz/src/hb-ft.cc:700
```

And again `calloc()` returns `NULL` a final time here, leading to the `NULL` dereference:

```
#0  0x0000000000d32009 in _hb_ft_font_create (ft_face=0x61a000003088, symbol=false, unref=false) at harfbuzz/src/hb-ft.cc:89
#1  0x0000000000d31215 in _hb_ft_font_set_funcs (font=0x60d0000006c8, ft_face=0x61a000003088, unref=false) at harfbuzz/src/hb-ft.cc:563
#2  0x0000000000d310e6 in hb_ft_font_create (ft_face=0x61a000003088, destroy=0x0) at harfbuzz/src/hb-ft.cc:700
```

Looking at the [source code](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ft.cc#L94) `ft_font` will be set to `NULL` in` _hb_ft_font_create()`. This means that `hb_font_set_funcs()` is called with `font_data` being `NULL`, and [therefore sets](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-font.cc#L1713) `font->user_data` to `NULL`. After `_hb_ft_font_set_funcs()` is finished `hb_ft_font_create()` will [continue calling](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ft.cc#L811) `hb_ft_font_changed()`, which will set `ft_font` to the value of `font->user_data` (`NULL` according to above). Finally `hb_ft_font_changed()` will [dereference](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-ft.cc#L832) `ft_font`.

**Comment by behdad** [comment]
Again, spot on! In every case I look for bailing out earlier so we don't get into destructor functions with null, but in every case I agree with you this is better way. :)

Let's start prefixing commits for these fixes with "[ENOMEM]".
