### ISSUE TITLE
msys2 build failure on meson

### ISSUE THREAD

**Issue by ebraminio** [harfbuzz/harfbuzz#2561]
We have a meson configure failure after meson update to 0.55 which only happens in msys2 which I have less tools for testing locally, maybe this is happening with older versions of gir's meson support? https://ci.appveyor.com/project/harfbuzz/harfbuzz/builds/34050794/job/gpj95udn3owvw817 

@lazka are you interested to have a look as it may stops msys2's harfbuzz package build also? It feels really out of harfbuzz meson support hands so maybe is either msys2 failure or meson?

One other issue happened after 0.55 upgrade is also filed here https://github.com/mesonbuild/meson/issues/7437 so guess packagers should be careful about an upgrade to it.

```
meson build --wrap-mode=nofallback -Dfreetype=enabled -Dglib=enabled -Dcairo=enabled -Dgobject=enabled -Dgdi=enabled -Ddirectwrite=enabled -Dgraphite=enabled && meson test -Cbuild --print-errorlogs

Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\mesonmain.py", line 131, in run
    return options.run_func(options)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\msetup.py", line 245, in run
    app.generate()
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\msetup.py", line 159, in generate
    self._generate(env)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\msetup.py", line 192, in _generate
    intr.run()
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreter.py", line 4546, in run
    super().run()
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 493, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 524, in evaluate_statement
    return self.function_call(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 881, in function_call
    return func(node, func_args, self.kwargs_string_keys(kwargs))
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreter.py", line 4067, in func_subdir
    self.evaluate_codeblock(codeblock)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 534, in evaluate_statement
    return self.evaluate_if(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 615, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 534, in evaluate_statement
    return self.evaluate_if(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 615, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 518, in evaluate_codeblock
    raise e
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 511, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 526, in evaluate_statement
    self.assignment(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 1179, in assignment
    value = self.evaluate_statement(node.value)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 528, in evaluate_statement
    return self.method_call(cur)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 923, in method_call
    return obj.method_call(method_name, args, self.kwargs_string_keys(kwargs))
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreter.py", line 1816, in method_call
    value = fn(state, args, kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 378, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\interpreterbase.py", line 213, in wrapped
    return f(*wrapped_args, **wrapped_kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\modules\gnome.py", line 765, in generate_gir
    self._get_dependencies_flags(deps, state, depends, use_gir_args=True)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\modules\gnome.py", line 371, in _get_dependencies_flags
    if use_gir_args and self._gir_has_option('--extra-library'):
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\modules\gnome.py", line 434, in _gir_has_option
    p, o, e = Popen_safe(exe.get_command() + ['--help'], stderr=subprocess.STDOUT)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\mesonlib.py", line 1197, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdout=stdout, stderr=stderr, **kwargs)
  File "C:/msys64/mingw64/lib/python3.7/site-packages\mesonbuild\mesonlib.py", line 1214, in Popen_safe_legacy
    stdout=stdout, stderr=stderr, **kwargs)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 1119, in _execute_child
    args = list2cmdline(args)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
The Meson build system
Version: 0.55.0
```

**Comment by lazka** [comment]
I'll have a look

**Comment by lazka** [comment]
The problem is this line `g_ir_scanner=${bindir}/g-ir-scanner` in `gobject-introspection-1.0.pc`. Meson expands it and then throws it out because it's missing a file extension (in _search_windows_special_cases()), and then never checks if it succeeded.

So, the .pc file in MSYS2 needs to be fixed and append '.exe' there.

**Comment by ebraminio** [comment]
> I'd suggest to use the MSYS2 provided meson as a workaround for now.

Sure, https://github.com/harfbuzz/harfbuzz/commit/51a8eb1c028ba430986bbe4b1e6afaf0063a6f76

**Comment by ebraminio** [comment]
And thank you so much for investigating it :) Should we close this?

**Comment by lazka** [comment]
I've filed https://github.com/msys2/MINGW-packages/issues/6677 with MSYS2. Feel free to close.

**Comment by ebraminio** [comment]
Thank you very much :)
