### ISSUE TITLE
[subset] GPOS lookupType 9 not properly subset.

### ISSUE THREAD

**Issue by bungeman** [harfbuzz/harfbuzz#2580]
With HarfBuzz 83c44f69d3724acbb16b25c1c1dee564ca1c3604 with [Lato-Medium.ttf](https://github.com/latofonts/lato-source/blob/353ba57fb6a82049e1dc116d8180ebfbbefc1474/fonts/static/TTF/Lato-Medium.ttf).

```
~/src/harfbuzz$ ./autogen.sh --prefix=$HOME/src/harfbuzz/usr
Build configuration:

Unicode callbacks (you want at least one):
        Builtin                 true
        Glib:                   true
        ICU:                    true

Font callbacks (the more the merrier):
        FreeType:               true

Tools used for command-line utilities:
        Cairo:                  true
        Fontconfig:             true

Additional shapers:
        Graphite2:              false

Platform shapers (not normally needed):
        CoreText:               false
        DirectWrite:            false
        GDI:                    false
        Uniscribe:              false

Other features:
        Documentation:          no
        GObject bindings:       false
        Introspection:          false

~/src/harfbuzz$ make -j32 install
~/src/harfbuzz$ usr/bin/hb-subset --drop-tables-="GSUB GPOS GDEF" -o Lato-Liga.ttf Lato-Medium.ttf "fistﬆﬁ "
```
This runs fine but produces a bad GPOS table. This was initially detected with ttx running like
```
~/src/harfbuzz$ ttx Lato-Liga.ttf
Dumping "src/harfbuzz/Lato-Liga.ttf" to "src/harfbuzz/Lato-Liga.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'GDEF' table...
ERROR: An exception occurred during the decompilation of the 'GPOS' table
Traceback (most recent call last):
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 372, in __getitem__
    return self.tables[tag]
KeyError: 'GPOS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/ttFont.py", line 391, in __getitem__
    table.decompile(data, self)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 41, in decompile
    self.table.decompile(reader, font)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 622, in decompile
    table[conv.name] = conv.read(reader, font, table)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 550, in read
    table.decompile(reader, font)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 618, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 166, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 550, in read
    table.decompile(reader, font)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 618, in decompile
    table[conv.name] = conv.readArray(reader, font, table, countValue)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 166, in readArray
    l.append(self.read(reader, font, tableDict))
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 550, in read
    table.decompile(reader, font)
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otBase.py", line 601, in decompile
    conv = conv.getConverter(reader.tableTag,
  File "/home/bungeman/src/fonttools/Lib/fontTools/ttLib/tables/otConverters.py", line 586, in getConverter
    tableClass = self.lookupTypes[tableType][lookupType]
KeyError: (20, 'SubTable', 'Lookup', 'LookupList')
Dumping 'GPOS' table...
Dumping 'GSUB' table...
```

**Comment by bungeman** [comment]
This is due to the subset GPOS LookupTables. In the original Lato-Medium.ttf font all of the LookupTables are lookupType 9. In the original font the LookupTables look like
```
00 09 00 08 00 09 00 18 00 20 00 28 00 30 00 38
00 40 00 48 00 50 00 58 00 01 00 02 00 00 01 18
00 01 00 02 00 00 94 A4 00 01 00 02 00 01 45 CA
00 01 00 02 00 01 D6 D0 00 01 00 02 00 02 04 2A
00 01 00 02 00 02 2F AE 00 01 00 02 00 02 5A D2
00 01 00 02 00 02 A0 98 00 01 00 02 00 02 AE B8

lookupType 00 09
lookupFlag 00 08 //ignoreMarks
subTableCount 00 09
subtableOffsets
00 18
00 20
00 28
00 30
00 38
00 40
00 48
00 50
00 58
markFilteringSet (not present, 0x10 not in lookupFlag)

subtable @ 00 18
posFormat 00 01
extensionLookupType 00 02
extensionOffset 00 00 01 18

subtable @ 00 20
posFonrmat 00 01
extensionLookupType 00 02
extensionOffset 00 00 94 A4

... and the rest of the similar subtables ...
00 01 00 02 00 01 45 CA
00 01 00 02 00 01 D6 D0
00 01 00 02 00 02 04 2A
00 01 00 02 00 02 2F AE
00 01 00 02 00 02 5A D2
00 01 00 02 00 02 A0 98
00 01 00 02 00 02 AE B8
```
In the subset font the LookupTables look like
```
00 09 00 08 00 02 00 CA 00 0A 00 02 00 42 00 04
00 00 00 8C 00 5E 00 05 00 05 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 04
00 02 00 0A 00 00 00 0C 00 0D 00 09 00 0F 00 10
00 0B 00 17 00 18 00 0D 00 02 00 07 00 02 00 07
00 01 00 08 00 08 00 02 00 09 00 0A 00 04 00 0B
00 0B 00 01 00 0C 00 0D 00 03 00 0F 00 10 00 03
00 17 00 18 00 03 00 01 00 02 00 17 00 01 00 01
00 02 00 02 00 04 00 04 00 02 00 03 00 04 00 00
00 04 00 01 00 00 00 04 00 01 00 00 00 00 00 00
00 00 00 00 00 00 00 02 00 02 00 01 00 14 00 04
00 00 00 04 00 20 00 20 00 20 00 20 00 00 00 01
00 04 00 02 00 03 00 0D 00 10 00 01 00 01 FF DB

lookupType 00 09
lookupFlag 00 08 //ignoreMarks
subTableCount 00 02
subtableOffsets
00 CA
00 0A
markFilteringSet (not present, 0x10 not in lookupFlag)

subtable @ 00 0A
00 02 00 42 00 04 00 00 00 8C 00 5E 00 05 00 05
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 02 00 04 00 02 00 0A 00 00 00 0C 00 0D
00 09 00 0F 00 10 00 0B 00 17 00 18 00 0D 00 02
00 07 00 02 00 07 00 01 00 08 00 08 00 02 00 09
00 0A 00 04 00 0B 00 0B 00 01 00 0C 00 0D 00 03
00 0F 00 10 00 03 00 17 00 18 00 03 00 01 00 02
00 17 00 01 00 01 00 02 00 02 00 04 00 04 00 02
00 03 00 04 00 00 00 04 00 01 00 00 00 04 00 01
00 00 00 00 00 00 00 00 00 00 00 00 00 02 00 02

subtable @ 00 CA
00 01 00 14 00 04 00 00 00 04 00 20 00 20 00 20
00 20 00 00 00 01 00 04 00 02 00 03 00 0D 00 10
00 01 00 01 FF DB
```
The lookupType in the subset font is 9, but the subtables written out do not reflect this. It looks like the subtables were placed here directly without going through a lookupType 9 indirection (or the subset lookupType should have been changed to match).

**Comment by bungeman** [comment]
It appears that the lookupType is written out in Lookup::subset and is the original lookup type (in this case 9). However, when it goes to write out the subtables the ExtensionPos just passes everything through and ExtensionFormat1 doesn't have a 'subset' method so the underlying lookup data is written out and the lookup refers to them instead.

**Comment by garretrieger** [comment]
As you noted we haven't implemented subsetting for Extension lookup types yet. That should be coming pretty soon though. I believe it's one of the last lookup types that we have to implement support for.

**Comment by bungeman** [comment]
Created https://github.com/harfbuzz/harfbuzz/pull/2582 which is the smallest change I can come up with which should work to at least not create small broken fonts. It at least unblocks my current use case.

**Comment by behdad** [comment]
Fixing in https://github.com/harfbuzz/harfbuzz/pull/2705
