### ISSUE TITLE
gen-use-table is failing

### ISSUE THREAD

**Issue by simoncozens** [harfbuzz/harfbuzz#2702]
```
$ python3 src/gen-use-table.py ~/.youseedee/IndicSyllabicCategory.txt ~/.youseedee/IndicPositionalCategory.txt ~/.youseedee/UnicodeData.txt ~/.youseedee/ArabicShaping.txt ~/.youseedee/Blocks.txt src/ms-use/IndicPositionalCategory-Additional.txt src/ms-use/IndicSyllabicCategory-Additional.txt
Traceback (most recent call last):
  File "src/gen-use-table.py", line 463, in <module>
    data = map_to_use(data)
  File "src/gen-use-table.py", line 456, in map_to_use
    assert len(values) == 1, "%s %s %s %s %s %s %s" % (hex(U), UIPC, USE, UISC, UGC, AJT, values)
AssertionError: 0xf7f Consonant_Dead VM Visarga Mc jt_X []
```

**Comment by simoncozens** [comment]
Started failing as of 06f49fc8a. This is with the latest UCD.

**Comment by behdad** [comment]
Cc @dscorbett

**Comment by dscorbett** [comment]
You swapped the last two arguments.

**Comment by simoncozens** [comment]
D'oh.
