### ISSUE TITLE
Build with LLVM 12 and Clang LTO Fails with check-static-inits. Meson replace linker.

### ISSUE THREAD

**Issue by h0tc0d3** [harfbuzz/harfbuzz#3019]
Build with LLVM 12 and Clang LTO  Fails: harfbuzz:src / check-static-inits FAIL. Meson replace linker.

```bash
export CC=clang
export CXX=clang++
export LD=ld.lld
export CC_LD=lld
export CXX_LD=lld
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export HOSTLD=ld.lld

export CPPFLAGS="-D_FORTIFY_SOURCE=2"
export CFLAGS="-fdiagnostics-color=always -pipe -O2 -march=native -fstack-protector-strong"
export CXXFLAGS="-fdiagnostics-color=always -pipe -O2 -march=native -fstack-protector-strong -fuse-ld=lld"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

meson harfbuzz build \
  --prefix /usr \
  --libexecdir lib \
  --sbindir bin \
  --auto-features enabled \
  --wrap-mode=nodownload \
  -D debug=false \
  -D optimization=2 \
  -D b_ndebug=true \
  -D b_lto=true \
  -D b_lto_mode=thin \
  -D glib=enabled \
  -D gobject=enabled \
  -D cairo=enabled \
  -D icu=enabled \
  -D graphite=enabled \
  -D freetype=enabled \
  -D chafa=enabled \
  -D introspection=enabled

```

`file hb-icu.cc.o` return `hb-icu.cc.o: LLVM IR bitcode`

<details>
  <summary>Error log</summary>

```text

22/361 harfbuzz:src / check-static-inits                                 FAIL             0.08s   exit status 1
>>> builddir=/tmp/makepkg/harfbuzz/src/build/src HBHEADERS='src/hb-aat-layout.h src/hb-aat.h src/hb-blob.h src/hb-buffer.h src/hb-common.h src/hb-deprecated.h src/hb-draw.h src/hb-face.h src/hb-font.h src/hb-map.h src/hb-ot-color.h src/hb-ot-deprecated.h src/hb-ot-font.h src/hb-ot-layout.h src/hb-ot-math.h src/hb-ot-meta.h src/hb-ot-metrics.h src/hb-ot-name.h src/hb-ot-shape.h src/hb-ot-var.h src/hb-ot.h src/hb-set.h src/hb-shape-plan.h src/hb-shape.h src/hb-style.h src/hb-unicode.h src/hb.h src/hb-version.h src/hb-ft.h src/hb-graphite2.h src/hb-glib.h' MALLOC_PERTURB_=31 libs=/tmp/makepkg/harfbuzz/src/build/src srcdir=/tmp/makepkg/harfbuzz/src/harfbuzz/src HBSOURCES='src/hb-aat-layout-ankr-table.hh src/hb-aat-layout-bsln-table.hh src/hb-aat-layout-common.hh src/hb-aat-layout-feat-table.hh src/hb-aat-layout-just-table.hh src/hb-aat-layout-kerx-table.hh src/hb-aat-layout-morx-table.hh src/hb-aat-layout-opbd-table.hh src/hb-aat-layout-trak-table.hh src/hb-aat-layout.cc src/hb-aat-layout.hh src/hb-aat-ltag-table.hh src/hb-aat-map.cc src/hb-aat-map.hh src/hb-algs.hh src/hb-array.hh src/hb-atomic.hh src/hb-bimap.hh src/hb-blob.cc src/hb-blob.hh src/hb-buffer-serialize.cc src/hb-buffer.cc src/hb-buffer.hh src/hb-cache.hh src/hb-cff-interp-common.hh src/hb-cff-interp-cs-common.hh src/hb-cff-interp-dict-common.hh src/hb-cff1-interp-cs.hh src/hb-cff2-interp-cs.hh src/hb-common.cc src/hb-config.hh src/hb-debug.hh src/hb-dispatch.hh src/hb-draw.cc src/hb-draw.hh src/hb-face.cc src/hb-face.hh src/hb-fallback-shape.cc src/hb-font.cc src/hb-font.hh src/hb-iter.hh src/hb-kern.hh src/hb-machinery.hh src/hb-map.cc src/hb-map.hh src/hb-meta.hh src/hb-mutex.hh src/hb-null.hh src/hb-number.cc src/hb-number.hh src/hb-object.hh src/hb-open-file.hh src/hb-open-type.hh src/hb-ot-cff-common.hh src/hb-ot-cff1-std-str.hh src/hb-ot-cff1-table.cc src/hb-ot-cff1-table.hh src/hb-ot-cff2-table.cc src/hb-ot-cff2-table.hh src/hb-ot-cmap-table.hh src/hb-ot-color-cbdt-table.hh src/hb-ot-color-colr-table.hh src/hb-ot-color-cpal-table.hh src/hb-ot-color-sbix-table.hh src/hb-ot-color-svg-table.hh src/hb-ot-color.cc src/hb-ot-face-table-list.hh src/hb-ot-face.cc src/hb-ot-face.hh src/hb-ot-font.cc src/hb-ot-gasp-table.hh src/hb-ot-glyf-table.hh src/hb-ot-hdmx-table.hh src/hb-ot-head-table.hh src/hb-ot-hhea-table.hh src/hb-ot-hmtx-table.hh src/hb-ot-kern-table.hh src/hb-ot-layout-base-table.hh src/hb-ot-layout-common.hh src/hb-ot-layout-gdef-table.hh src/hb-ot-layout-gpos-table.hh src/hb-ot-layout-gsub-table.hh src/hb-ot-layout-gsubgpos.hh src/hb-ot-layout-jstf-table.hh src/hb-ot-layout.cc src/hb-ot-layout.hh src/hb-ot-map.cc src/hb-ot-map.hh src/hb-ot-math-table.hh src/hb-ot-math.cc src/hb-ot-maxp-table.hh src/hb-ot-meta-table.hh src/hb-ot-meta.cc src/hb-ot-metrics.cc src/hb-ot-metrics.hh src/hb-ot-name-language-static.hh src/hb-ot-name-language.hh src/hb-ot-name-table.hh src/hb-ot-name.cc src/hb-ot-os2-table.hh src/hb-ot-os2-unicode-ranges.hh src/hb-ot-post-macroman.hh src/hb-ot-post-table.hh src/hb-ot-shape-complex-arabic-fallback.hh src/hb-ot-shape-complex-arabic-joining-list.hh src/hb-ot-shape-complex-arabic-table.hh src/hb-ot-shape-complex-arabic-win1256.hh src/hb-ot-shape-complex-arabic.cc src/hb-ot-shape-complex-arabic.hh src/hb-ot-shape-complex-default.cc src/hb-ot-shape-complex-hangul.cc src/hb-ot-shape-complex-hebrew.cc src/hb-ot-shape-complex-indic-table.cc src/hb-ot-shape-complex-indic.cc src/hb-ot-shape-complex-indic.hh src/hb-ot-shape-complex-khmer.cc src/hb-ot-shape-complex-khmer.hh src/hb-ot-shape-complex-myanmar.cc src/hb-ot-shape-complex-myanmar.hh src/hb-ot-shape-complex-syllabic.cc src/hb-ot-shape-complex-syllabic.hh src/hb-ot-shape-complex-thai.cc src/hb-ot-shape-complex-use-table.hh src/hb-ot-shape-complex-use.cc src/hb-ot-shape-complex-vowel-constraints.cc src/hb-ot-shape-complex-vowel-constraints.hh src/hb-ot-shape-complex.hh src/hb-ot-shape-fallback.cc src/hb-ot-shape-fallback.hh src/hb-ot-shape-normalize.cc src/hb-ot-shape-normalize.hh src/hb-ot-shape.cc src/hb-ot-shape.hh src/hb-ot-stat-table.hh src/hb-ot-tag-table.hh src/hb-ot-tag.cc src/hb-ot-var-avar-table.hh src/hb-ot-var-fvar-table.hh src/hb-ot-var-gvar-table.hh src/hb-ot-var-hvar-table.hh src/hb-ot-var-mvar-table.hh src/hb-ot-var.cc src/hb-ot-vorg-table.hh src/hb-pool.hh src/hb-sanitize.hh src/hb-serialize.hh src/hb-set-digest.hh src/hb-set.cc src/hb-set.hh src/hb-shape-plan.cc src/hb-shape-plan.hh src/hb-shape.cc src/hb-shaper-impl.hh src/hb-shaper-list.hh src/hb-shaper.cc src/hb-shaper.hh src/hb-static.cc src/hb-string-array.hh src/hb-style.cc src/hb-ucd-table.hh src/hb-ucd.cc src/hb-unicode-emoji-table.hh src/hb-unicode.cc src/hb-unicode.hh src/hb-utf.hh src/hb-vector.hh src/hb.hh src/hb-buffer-deserialize-json.hh src/hb-buffer-deserialize-text.hh src/hb-number-parser.hh src/hb-ot-shape-complex-indic-machine.hh src/hb-ot-shape-complex-khmer-machine.hh src/hb-ot-shape-complex-myanmar-machine.hh src/hb-ot-shape-complex-use-machine.hh src/hb-ft.cc src/hb-graphite2.cc src/hb-glib.cc' /tmp/makepkg/harfbuzz/src/harfbuzz/src/check-static-inits.py
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stderr:
/usr/bin/objdump: /tmp/makepkg/harfbuzz/src/build/src/libharfbuzz-icu.so.0.20801.0.p/hb-icu.cc.o: file format not recognized
Traceback (most recent call last):
  File "/tmp/makepkg/harfbuzz/src/harfbuzz/src/check-static-inits.py", line 25, in <module>
    result = subprocess.check_output ([objdump, '-t', obj]).decode ('utf-8')
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/objdump', '-t', '/tmp/makepkg/harfbuzz/src/build/src/libharfbuzz-icu.so.0.20801.0.p/hb-icu.cc.o']' returned non-zero exit status 1.

```
</details>

**Comment by khaledhosny** [comment]
You probably need to set `CXX_LD` ebv variable as well: https://mesonbuild.com/howtox.html#set-linker

**Comment by h0tc0d3** [comment]
I already tried to set CXX_LD. Not helped for me.

**Comment by behdad** [comment]
We should adjust the test to skip if object files are not recognized.
```
/usr/bin/objdump: /tmp/makepkg/harfbuzz/src/build/src/libharfbuzz-icu.so.0.20801.0.p/hb-icu.cc.o: file format not recognized
```

**Comment by behdad** [comment]
Not sure how best to do that.

**Comment by h0tc0d3** [comment]
I maked tempory solution.

```bash
sed -i "s/'check-static-inits',//" src/meson.build
```

**Comment by behdad** [comment]
Oh, using `$(OBJDUMP)` should help. Let me try.

**Comment by behdad** [comment]
Proposed fix in https://github.com/harfbuzz/harfbuzz/pull/3024
Let us know if it doesn't work for you. Thanks.

**Comment by h0tc0d3** [comment]
Thank you. Not helped for me.

**Comment by behdad** [comment]
> Thank you. Not helped for me. The same error.

So, still says `/usr/bin/objdump` in the error?

**Comment by behdad** [comment]
Oh, you probably are building using meson. Need a way for meson to pass down those same vars as well.

**Comment by behdad** [comment]
Someone who knows meson should add the equivalent of my `Makefile.am` change I suppose.

**Comment by h0tc0d3** [comment]
```
So, still says /usr/bin/objdump in the error?
```
No, llvm-objdump. But llvm-objdump show the same error. I think because meson and clang not using lld as default linker.

**Comment by behdad** [comment]
> ```
> So, still says /usr/bin/objdump in the error?
> ```
> 
> No, llvm-objdump. But llvm-objdump show the same error. I think because meson and clang not using lld as default linker.

No I think what you are getting is an inherent result of LTO. In LTO mode, the `.o` "object files" are in fact LLVM bitcode. So running `objdump` doesn't work on them. Apparently not even `llvm-objdump` works on them.

We should just detect that and skip the test.

**Comment by behdad** [comment]
@h0tc0d3 Okay, pushed another fix. Please try.

**Comment by h0tc0d3** [comment]
@behdad thank you! All fine!
