### ISSUE TITLE
Compile error ocurred while building harfbuzz 3.0.0 on Debian

### ISSUE THREAD

**Issue by Arlen-LT** [harfbuzz/harfbuzz#3227]
I have run the command to configure the env as https://github.com/harfbuzz/harfbuzz/blob/main/BUILD.md said:
```
sudo apt-get install pkg-config ragel gtk-doc-tools libfreetype6-dev libglib2.0-dev libcairo2-dev
```
and then I run a shell script:
```
unset CC CXX # meson wants these unset

meson $build \
	--buildtype release --cross-file "$prefix_dir"/crossfile.txt \
	--default-library static -Dtests=disabled
meson compile -C $build -j$cores
DESTDIR="$out_dir" meson install -C $build
```
The log is as followed:
```
The Meson build system
Version: 0.56.2
Source dir: harfbuzz
Build dir: harfbuzz/build
Build type: cross build
Project name: harfbuzz
Project version: 3.0.0
C compiler for the host machine: armv7a-linux-androideabi21-clang (clang 9.0.9 "Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)")
C linker for the host machine: armv7a-linux-androideabi21-clang ld.gold 2.27.0.20170315
C++ compiler for the host machine: armv7a-linux-androideabi21-clang++ (clang 9.0.9 "Android (7019983 based on r365631c3) clang version 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) (based on LLVM 9.0.9svn)")
C++ linker for the host machine: armv7a-linux-androideabi21-clang++ ld.gold 2.27.0.20170315
C compiler for the build machine: cc (gcc 6.3.0 "cc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516")
C linker for the build machine: cc ld.bfd 2.28
C++ compiler for the build machine: c++ (gcc 6.3.0 "c++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516")
C++ linker for the build machine: c++ ld.bfd 2.28
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: arm
Target machine cpu: armv7a
Compiler for C++ supports link arguments -Bsymbolic-functions: YES (cached)
Compiler for C++ supports arguments -fno-exceptions: YES (cached)
Compiler for C++ supports arguments -fno-rtti: YES (cached)
Compiler for C++ supports arguments -fno-threadsafe-statics: YES (cached)
Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES (cached)
Checking for alignment of "struct { char c; }" : 1
Library m found: YES
Dependency freetype2 found: YES 23.4.17 (cached)
Dependency glib-2.0 found: YES 2.50.3 (cached)
Dependency gobject-2.0 found: YES 2.50.3 (cached)
Dependency graphite2 skipped: feature graphite disabled
Dependency icu-uc found: YES 57.1 (cached)
Found pkg-config: /usr/bin/pkg-config (0.29)
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/bin/pkg-config'
Run-time dependency cairo found: YES 1.14.8
Using 'PKG_CONFIG_PATH' from environment with value: '/usr/bin/pkg-config'
Run-time dependency cairo-ft found: YES 1.14.8
Found CMake: NO
Run-time dependency chafa found: NO (tried pkgconfig and cmake)
Compiler for C++ supports arguments -Wno-non-virtual-dtor: YES (cached)
Dependency threads found: YES unknown (cached)
Has header "unistd.h" : YES (cached)
Has header "sys/mman.h" : YES (cached)
Has header "stdbool.h" : YES (cached)
Checking for function "atexit" : YES (cached)
Checking for function "mprotect" : YES (cached)
Checking for function "sysconf" : YES (cached)
Checking for function "getpagesize" : YES (cached)
Checking for function "mmap" : YES (cached)
Checking for function "isatty" : YES (cached)
Checking for function "FT_Get_Var_Blend_Coordinates" with dependency freetype2: NO (cached)
Checking for function "FT_Set_Var_Blend_Coordinates" with dependency freetype2: NO (cached)
Checking for function "FT_Done_MM_Var" with dependency freetype2: NO (cached)
Program gen-hb-version.py found: YES (/harfbuzz/src/gen-hb-version.py)
Configuring hb-version.h with command

../src/meson.build:1:0: ERROR: Running configure command failed.

Traceback (most recent call last):
  File "/harfbuzz/src/gen-hb-version.py", line 19, in <module>
    for line in old_output:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)
```

and while building for the first time without caches, it print errors like:
```
[42/81] Compiling C++ object src/libharfbuzz.a.p/hb-unicode.cc.o
FAILED: src/libharfbuzz.a.p/hb-unicode.cc.o
armv7a-linux-androideabi21-clang++ -Isrc/libharfbuzz.a.p -Isrc -I../src -I. -I.. -I/usr/local/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -fPIC -pthread -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz.a.p/hb-unicode.cc.o -MF src/libharfbuzz.a.p/hb-unicode.cc.o.d -o src/libharfbuzz.a.p/hb-unicode.cc.o -c ../src/hb-unicode.cc
In file included from ../src/hb-unicode.cc:135:
In file included from ../src/hb-glib.h:34:
In file included from /usr/include/glib-2.0/glib.h:30:
In file included from /usr/include/glib-2.0/glib/galloca.h:32:
/usr/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:232:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
In file included from ../src/hb-unicode.cc:135:
In file included from ../src/hb-glib.h:34:
In file included from /usr/include/glib-2.0/glib.h:30:
In file included from /usr/include/glib-2.0/glib/galloca.h:32:
/usr/include/glib-2.0/glib/gtypes.h:424:43: error: cast from 'guint64 *' (aka 'unsigned long *') to 'unsigned long long *' increases required alignment from 4 to 8 [-Werror,-Wcast-align]
  return !__builtin_uaddll_overflow(a, b, (unsigned long long *) dest); }
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:426:43: error: cast from 'guint64 *' (aka 'unsigned long *') to 'unsigned long long *' increases required alignment from 4 to 8 [-Werror,-Wcast-align]
  return !__builtin_umulll_overflow(a, b, (unsigned long long *) dest); }
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
[43/81] Compiling C++ object src/libharfbuzz.a.p/hb-ft.cc.o
FAILED: src/libharfbuzz.a.p/hb-ft.cc.o
armv7a-linux-androideabi21-clang++ -Isrc/libharfbuzz.a.p -Isrc -I../src -I. -I.. -I/usr/local/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -fPIC -pthread -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz.a.p/hb-ft.cc.o -MF src/libharfbuzz.a.p/hb-ft.cc.o.d -o src/libharfbuzz.a.p/hb-ft.cc.o -c ../src/hb-ft.cc
In file included from ../src/hb-ft.cc:34:
../src/hb-ft.h:34:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
[45/81] Compiling C++ object src/libharfbuzz.a.p/hb-glib.cc.o
FAILED: src/libharfbuzz.a.p/hb-glib.cc.o
armv7a-linux-androideabi21-clang++ -Isrc/libharfbuzz.a.p -Isrc -I../src -I. -I.. -I/usr/local/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -fno-rtti -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -fPIC -pthread -Wno-non-virtual-dtor -MD -MQ src/libharfbuzz.a.p/hb-glib.cc.o -MF src/libharfbuzz.a.p/hb-glib.cc.o.d -o src/libharfbuzz.a.p/hb-glib.cc.o -c ../src/hb-glib.cc
In file included from ../src/hb-glib.cc:33:
In file included from ../src/hb-glib.h:34:
In file included from /usr/include/glib-2.0/glib.h:30:
In file included from /usr/include/glib-2.0/glib/galloca.h:32:
/usr/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:232:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
In file included from ../src/hb-glib.cc:33:
In file included from ../src/hb-glib.h:34:
In file included from /usr/include/glib-2.0/glib.h:30:
In file included from /usr/include/glib-2.0/glib/galloca.h:32:
/usr/include/glib-2.0/glib/gtypes.h:424:43: error: cast from 'guint64 *' (aka 'unsigned long *') to 'unsigned long long *' increases required alignment from 4 to 8 [-Werror,-Wcast-align]
  return !__builtin_uaddll_overflow(a, b, (unsigned long long *) dest); }
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:426:43: error: cast from 'guint64 *' (aka 'unsigned long *') to 'unsigned long long *' increases required alignment from 4 to 8 [-Werror,-Wcast-align]
  return !__builtin_umulll_overflow(a, b, (unsigned long long *) dest); }
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
```
Is it a cross compile error? And how to solve it? Thanks for any answer.

**Comment by khaledhosny** [comment]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)

`src/hb-version.h` is UTF-8 encoded, but your Python’s default encoding is ASCII for some reason. We probably should explicitely open the file with `utf-8` encoding.

**Comment by Arlen-LT** [comment]
> > UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)
> 
> `src/hb-version.h` is UTF-8 encoded, but your Python’s default encoding is ASCII for some reason. We probably should explicitly open the file with `utf-8` encoding.

I checked my python3 default encoding, it is "UTF-8".
user@host:$ python3
Python 3.5.3 (default, Apr  5 2021, 09:00:41)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'

**Comment by khaledhosny** [comment]
`open()` uses (per its documentation) `locale.getpreferredencoding(False)`.

**Comment by Arlen-LT** [comment]
> `open()` uses (per its documentation) `locale.getpreferredencoding(False)`.

Thanks a lot.
```
$ python3 -c 'import locale; print(locale.getpreferredencoding())'
ANSI_X3.4-1968
```
To solve it permanently, here is my method sharing for everyone:

step1. `vi /etc/default/locale`
step2. modify `LC_ALL=en_US.UTF8` and `:wq`
step3. `source /etc/default/locale`
and then 
```
$ python3 -c 'import locale; print(locale.getpreferredencoding())'
UTF-8
```
Some other informations about this question may be helpful: https://stackoverflow.com/questions/44344458/why-does-locale-getpreferredencoding-return-ansi-x3-4-1968-instead-of-utf-8

**Comment by behdad** [comment]
> Is it a cross compile error?

It seems to be picking up wrong glib headers. So yes, cross-compile issue.

I fixed the Python issue.
