### ISSUE TITLE
out of memory in hb-subset-fuzzer

### ISSUE THREAD

**Issue by wangkerong** [harfbuzz/harfbuzz#3239]
```shell
./hb-subset-fuzzer: Running 1 inputs 1 time(s) each.
Running: fusiontest-testcase-hb-subset-fuzzer-202108170002
==2180229== ERROR: libFuzzer: out-of-memory (malloc(3895351660))
   To change the out-of-memory limit use -rss_limit_mb=<N>

    #0 0x52bc31 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:86:3
    #1 0x476b08 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x45a735 in fuzzer::Fuzzer::HandleMalloc(unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:131:3
    #3 0x45a64a in fuzzer::MallocHook(void const volatile*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:100:6
    #4 0x531f37 in __sanitizer::RunMallocHooks(void const*, unsigned long) /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_common.cpp:301:5
    #5 0x4a9290 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:611:5
    #6 0x4a8bd3 in __asan::asan_malloc(unsigned long, __sanitizer::BufferedStackTrace*) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:980:34
    #7 0x52339b in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:146:10
    #8 0x5b1f88 in hb_malloc_impl /work/build/../../src/harfbuzz/src/failing-alloc.c:41:31
    #9 0x570458 in _hb_face_builder_data_reference_blob(hb_face_builder_data_t*) /work/build/../../src/harfbuzz/src/hb-face.cc:677:24
    #10 0x564a4b in _hb_face_builder_reference_table(hb_face_t*, unsigned int, void*) /work/build/../../src/harfbuzz/src/hb-face.cc:707:12
    #11 0x563d1f in hb_face_t::reference_table(unsigned int) const /work/build/../../src/harfbuzz/src/hb-face.hh:77:12
    #12 0x563d82 in hb_face_reference_blob /work/build/../../src/harfbuzz/src/hb-face.cc:411:16
    #13 0x556d86 in trySubset(hb_face_t*, unsigned int const*, int, bool, bool, bool) /work/build/../../src/harfbuzz/test/fuzzing/hb-subset-fuzzer.cc:36:23
    #14 0x556b7d in trySubset(hb_face_t*, unsigned int const*, int, unsigned char const*) /work/build/../../src/harfbuzz/test/fuzzing/hb-subset-fuzzer.cc:62:3
    #15 0x55695d in LLVMFuzzerTestOneInput /work/build/../../src/harfbuzz/test/fuzzing/hb-subset-fuzzer.cc:86:3
    #16 0x45ce31 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #17 0x447942 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
    #18 0x44d856 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
    #19 0x4772d2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #20 0x7f7d62569b26 in __libc_start_main /usr/src/debug/glibc-2.28/csu/../csu/libc-start.c:308
    #21 0x422ec9 in _start (/root/hb-subset-fuzzer+0x422ec9)

DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::HandleMalloc(unsigned long)
SUMMARY: libFuzzer: out-of-memory
```

**Comment by garretrieger** [comment]
Can you provide the fuzzer input file that reproduces this?
