### ISSUE TITLE
31 test failures in shaping

### ISSUE THREAD

**Issue by themaddoctor** [harfbuzz/harfbuzz#533]
Tried both 1.4.8 and 1.5.0.

./configure --prefix=/usr --with-gobject --with-graphite2 --enable-introspection=no

Build configuration:
```
Unicode callbacks (you want at least one):
        Builtin (UCDN):         true
        Glib:                   true
        ICU:                    true

Font callbacks (the more the better):
        FreeType:               true

Tools used for command-line utilities:
        Cairo:                  true
        Fontconfig:             true

Additional shapers (the more the better):
        Graphite2:              true

Platform shapers (not normally needed):
        CoreText:               false
        Uniscribe:              false
        DirectWrite:            false

Other features:
        Documentation:          no
        GObject bindings:       true
        Introspection:          false
```

```
=================================================
   HarfBuzz 1.4.8: test/shaping/test-suite.log
=================================================

# TOTAL: 33
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  31
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/arabic-fallback-shaping
===================================

Running tests in ./tests/arabic-fallback-shaping.tests
Testing fonts/sha1sum/df768b9c257e0c9c35786c47cae15c46571d56be.ttf:U+0633,U+064F,U+0644,U+064E,U+0651,U+0627,U
+0651,U+0650,U+0645,U+062A,U+06CC
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)
Actual:
Expected: [uni06CC.fina=10+1655|uni062A.medi=9+868|uni0645.init=8+1098|uni0650=2@221,0+0|uni0651=2@260,736+0|u
ni064E=2@935,1259+0|uni0651=2@974,736+0|uni06440627.fina=2+1470|uni064F=0@558,-10+0|uni0633.init=0+1585]
1 tests failed.

FAIL: tests/arabic-feature-order
================================

Running tests in ./tests/arabic-feature-order.tests
Testing fonts/sha1sum/813c2f8e5512187fd982417a7fb4286728e6f4a8.ttf:U+1820,U+180B
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
Actual:
Expected: [uni2048.E81A=0+1550]
Testing fonts/sha1sum/8a9fea2a7384f2116e5b84a9b31f83be7850ce21.ttf:U+1820,U+180B
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
Actual:
Expected: [uni2048.E81A=0+1550]
Testing fonts/sha1sum/a919b33197965846f21074b24e30250d67277bce.ttf:U+0644,U+0644,U+0647
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)
Actual:
Expected: [Lellah=0+1503]
Testing fonts/sha1sum/bf39b0e91ef9807f15a9e283a21a14a209fd2cfc.ttf:U+0644,U+064E,U+0670,U+0653,U+0626
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
Actual:
Expected: [afii57414.zz04=4+1202|uni0670_uni0653=0@50,350+0|afii57454=0@550,1425+0|afii57444.calt=0+1065]
4 tests failed.

FAIL: tests/arabic-like-joining
===============================

Running tests in ./tests/arabic-like-joining.tests
Testing fonts/sha1sum/5dfad7735c6a67085f1b90d4d497e32907db4c78.ttf:U+1E922,U+1E923,U+1E924,U+1E925,U+1E926,U+1
E927,U+1E928,U+1E929,U+1E92A,U+1E92B,U+1E92C,U+1E92D,U+1E92E,U+1E92F,U+1E930,U+1E931,U+1E932,U+1E933,U+1E934,U
+1E935,U+1E936,U+1E937,U+1E938,U+1E939,U+1E93A,U+1E93B,U+1E93C,U+1E93D,U+1E93E,U+1E93F,U+1E940,U+1E941,U+1E942
,U+1E943
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-33: ordinal not in range(128)
Actual:
Expected: [sha_adlam.fina=33+711|kpo_adlam.medi=32+573|zal_adlam.medi=31+773|gbe_adlam.medi=30+594|kha_adlam.m
edi=29+686|va_adlam.medi=28+621|nha_adlam.medi=27+587|tu_adlam.medi=26+772|nya_adlam.medi=25+577|ga_adlam.medi
=24+552|qaaf_adlam.medi=23+694|ha_adlam.medi=22+600|chi_adlam.medi=21+662|jiim_adlam.medi=20+781|u_adlam.medi=
19+678|ya_adlam.medi=18+553|kaf_adlam.medi=17+808|nun_adlam.medi=16+561|waw_adlam.medi=15+651|yhe_adlam.medi=1
4+674|dha_adlam.medi=13+674|o_adlam.medi=12+640|i_adlam.medi=11+657|fa_adlam.medi=10+590|e_adlam.medi=9+628|ra
_adlam.medi=8+599|bhe_adlam.medi=7+594|pe_adlam.medi=6+492|sinnyiiyhe_adlam.medi=5+777|ba_adlam.medi=4+655|mii
m_adlam.medi=3+525|laam_adlam.medi=2+554|daali_adlam.medi=1+600|alif_adlam.init=0+597]
1 tests failed.

FAIL: tests/automatic-fractions
===============================

Running tests in ./tests/automatic-fractions.tests
Testing fonts/sha1sum/15dfc433a135a658b9f4b1a861b5cdd9658ccbb9.ttf:U+0031,U+0032,U+0033,U+2044,U+0034,U+0035,U
+0036
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2044' in position 3: ordinal not in range(128)
Actual:
Expected: [one.numr=0+600|two.numr=1+600|three.numr=2+600|fraction=3+252|four.small=4+600|five.small=5+600|six
.small=6+600]
Testing fonts/sha1sum/15dfc433a135a658b9f4b1a861b5cdd9658ccbb9.ttf:U+0031,U+0032,U+0033,U+2044,U+0034,U+0035,U
+0036
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2044' in position 3: ordinal not in range(128)
Actual:
Expected: [one.numr=0+600|two.numr=1+600|three.numr=2+600|fraction=3+252|four.small=4+600|five.small=5+600|six
.small=6+600]
Testing fonts/sha1sum/15dfc433a135a658b9f4b1a861b5cdd9658ccbb9.ttf:U+0661,U+0662,U+0663,U+2044,U+0664,U+0665,U
+0666
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
Actual:
Expected: [uni0661.numr=0+600|uni0662.numr=1+600|uni0663.numr=2+600|fraction=3+252|uni0664.small=4+600|uni0665
.small=5+600|uni0666.small=6+600]
3 tests failed.

FAIL: tests/cluster
===================

Running tests in ./tests/cluster.tests
Testing fonts/sha1sum/6466d38c62e73a39202435a4f73bf5d6acbb73c0.ttf:U+0078,U+030A,U+0058,U+030A
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode character '\u030a' in position 1: ordinal not in range(128)
Actual:
Expected: [gid2=0+1083|gid4=1@-555,-8+0|gid1=2+1200|gid4=3@-614,349+0]
Testing fonts/sha1sum/43ef465752be9af900745f72fe29cb853a1401a5.ttf:U+05D4,U+05B7,U+05E9,U+05BC,U+05C1,U+05B8,U
+05DE,U+05B4,U+05DD
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)
Actual:
Expected: [uni05DD=8+1359|uni05B4=7@111,0+0|uni05DE=6+1391|uni05B8=5+0|uni05BC=3+0|uni05C1=3+0|uni05E9=2+1451|
uni05B7=1@28,0+0|uni05D4=0+1338]
2 tests failed.

FAIL: tests/color-fonts
=======================

Running tests in ./tests/color-fonts.tests
Testing fonts/sha1sum/ee39587d13b2afa5499cc79e45780aa79293bbd4.ttf:U+1F42F
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f42f' in position 0: ordinal not in range(128)
Actual:
Expected: [gid1=0+2963<0,2178,2963,-2788>]
1 tests failed.

FAIL: tests/context-matching
============================

Running tests in ./tests/context-matching.tests
Testing fonts/sha1sum/4cce528e99f600ed9c25a2b69e32eb94a03b4ae8.ttf:U+1A48,U+1A58,U+1A25,U+1A48,U+1A58,U+1A25,U
+1A6E,U+1A63
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
Actual:
Expected: [uni1A48=0+1212|uni1A25=0+1912|uni1A58=0+0|uni1A48=3+1212|uni1A6E=3+0|uni1A25=3+1912|uni1A58=3+0|uni
1A63=3+1212]
Testing fonts/sha1sum/d629e7fedc0b350222d7987345fe61613fa3929a.ttf:U+0915,U+093F,U+0915,U+093F
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Actual:
Expected: [ivowelsign03deva=0+530|kadeva=0+1561|ivowelsign03deva=2+530|kadeva=2+1561]
Testing fonts/sha1sum/f499fbc23865022234775c43503bba2e63978fe1.ttf:U+09B0,U+09CD,U+09A5,U+09CD,U+09AF,U+09C0
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
Actual:
Expected: [gid1=0+1320|gid13=0+523|gid18=0+545]
3 tests failed.

FAIL: tests/cursive-positioning
===============================

Running tests in ./tests/cursive-positioning.tests
Testing fonts/sha1sum/c4e48b0886ef460f532fb49f00047ec92c432ec0.ttf:U+0643,U+0645,U+0645,U+062B,U+0644
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
Actual:
Expected: [gid8=4+738|gid5=3@441,1197+0|gid6=3@0,432+405|gid9=2@0,477+452|gid9=1@0,977+452|gid10=0@20,1577+207
]
Testing fonts/sha1sum/298c9e1d955f10f6f72c6915c3c6ff9bf9695cec.ttf:U+0643,U+0645,U+0645,U+062B,U+0644
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
Actual:
Expected: [gid8=4+738|gid5=3@441,1197+0|gid6=3@0,432+405|gid9=2@0,477+500|gid9=1@0,577+452|gid10=0@20,1177+207
]
Skipping #fonts/sha1sum/706c5d7b625f207bc0d874c67237aad6f1e9cd6f.ttf:U+0B1F,U+0B4D,U+0B1A,U+0B4D,U+0B1A
Testing fonts/sha1sum/07f054357ff8638bac3711b422a1e31180bba863.ttf:U+0606,U+06E1
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
Actual:
Expected: [2=0@40,502+0|1=0+1000]
3 tests failed.

FAIL: tests/default-ignorables
==============================

Running tests in ./tests/default-ignorables.tests
Testing fonts/sha1sum/051d92f8bc6ff724511b296c27623f824de256e9.ttf:U+0075,U+0361,U+034F,U+0301,U+0069
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-3: ordinal not in range(128)
Actual:
Expected: [gid2=0+1266|gid7=0@-617,442+0|gid5=0@-7,0+0|gid1=4+528]
1 tests failed.

FAIL: tests/emoji-flag-tags
===========================

Running tests in ./tests/emoji-flag-tags.tests
Testing fonts/sha1sum/53374c7ca3657be37efde7ed02ae34229a56ae1f.ttf:U+1F3F4,U+E0055,U+E0053,U+E0064,U+E0065,U+E
007F
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
Actual:
Expected: [u1F3F4=0+2126|space=1+0|space=2+0|space=3+0|space=4+0|space=5+0]
Testing fonts/sha1sum/53374c7ca3657be37efde7ed02ae34229a56ae1f.ttf:U+1F3F4,U+E0064,U+E0065,U+E007F
Traceback (most recent call last):
  File "./hb-unicode-encode", line 5, in <module>
    UtilMains.filter_multiple_strings_or_stdin (Unicode.encode, "UNICODE_STRING", '')
  File "/kaeding/harfbuzz/harfbuzz-1.4.8/test/shaping/hb_test_tools.py", line 448, in filter_multiple_strings_
or_stdin
    print (separator.join (callback (x) for x in (args)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Actual:
Expected: [de=0+3200]
2 tests failed.

FAIL: tests/fallback-positioning
================================
```

it goes on like that for a long while

**Comment by themaddoctor** [comment]
If I use python 2 instead of 3, then all 33 fail

**Comment by themaddoctor** [comment]
same result for a 64-bit build

**Comment by themaddoctor** [comment]
The problem is with python3. Closing

**Comment by behdad** [comment]
We actually like to fix that.  Although the test suite does NOT rely on python anymore (as of 1.5.1), but I like to fix this.

**Comment by behdad** [comment]
We actually like to fix that.  Although the test suite does NOT rely on python anymore (as of 1.5.1), but I like to fix this.

**Comment by behdad** [comment]
Any volunteers to port our Python stuff to py23?

**Comment by RevengeComing** [comment]
@behdad i already made something that works and tested on ubuntu/python3(2) and doesn't cover all functionality. and also i'm not sure if it has your standards. and it is made by Cython.

https://github.com/RevengeComing/pyharfbuzz

**Comment by anthrotype** [comment]
@RevengeComing cool that you worked on a cython wrapper for harfbuzz, i’ll check it out. However I think behdad was referring to the python scripts that are used for harfbuzz own test suite, rather than the bindings.

**Comment by RevengeComing** [comment]
@anthrotype  🤕 oh sorry
