### ISSUE TITLE
Undefined Behavior Sanitizer error in hb-ot-font.cc:142:82 - index 75 out of bounds for type 'LongMetric [1]'

### ISSUE THREAD

**Issue by pedronavf** [harfbuzz/harfbuzz#937]
Building harfbuzz in 32 bits mode with -fsanitize=undefined and running **hb-shape /usr/share/fonts/truetype/freefont/FreeSans.ttf --text="hello" --font-funcs=ot**

We get the same error reported in #935 but this time, as we are using the OT font functions, we also get:

`hb-ot-font.cc:142:82: runtime error: index 75 out of bounds for type 'LongMetric [1]'`

    #0 0xf7e1f23d in hb_ot_face_metrics_accelerator_t::get_advance(unsigned int, hb_font_t*) const (/home/pnavarro/test/lib/libharfbuzz.so.0+0x8823d)
    #1 0xf7e15c16 in hb_ot_get_glyph_h_advance /home/pnavarro/test/source/harfbuzz/src/hb-ot-font.cc:567
    #2 0xf7e04a05 in hb_font_t::get_glyph_h_advance(unsigned int) /home/pnavarro/test/source/harfbuzz/src/hb-font-private.hh:221
    #3 0xf7e8f25f in hb_ot_position_default /home/pnavarro/test/source/harfbuzz/src/hb-ot-shape.cc:671
    #4 0xf7e90045 in hb_ot_position /home/pnavarro/test/source/harfbuzz/src/hb-ot-shape.cc:769
    #5 0xf7e90e1f in hb_ot_shape_internal /home/pnavarro/test/source/harfbuzz/src/hb-ot-shape.cc:850
    #6 0xf7e9121a in _hb_ot_shape /home/pnavarro/test/source/harfbuzz/src/hb-ot-shape.cc:876
    #7 0xf7e10a8a in hb_shape_plan_execute /home/pnavarro/test/source/harfbuzz/src/hb-shaper-list.hh:43
    #8 0xf7e0fb67 in hb_shape_full /home/pnavarro/test/source/harfbuzz/src/hb-shape.cc:132
    #9 0x804b5c1 in shape_options_t::shape(hb_font_t*, hb_buffer_t*, char const**) (/home/pnavarro/test/bin/hb-shape+0x804b5c1)
    #10 0x804ed1a in shape_consumer_t<output_buffer_t>::consume_line(char const*, unsigned int, char const*, char const*) (/home/pnavarro/test/bin/hb-shape+0x804ed1a)
    #11 0x804e7a2 in main_font_text_t<shape_consumer_t<output_buffer_t>, 2147483647, 0>::main(int, char**) (/home/pnavarro/test/bin/hb-shape+0x804e7a2)
    #12 0x804a82d in main /home/pnavarro/test/source/harfbuzz/util/hb-shape.cc:162
    #13 0xf7217985 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18985)
    #14 0x804a500  (/home/pnavarro/test/bin/hb-shape+0x804a500)

**Comment by behdad** [comment]
Those are false positives.

**Comment by behdad** [comment]
This one we cannot easily silence. But it's not a bug.
